Bug: More informed reaping
- Only reap containers that aren't building.  If two containers are
  quickly deployed, the second container (the most recent code changes)
  will get reaped by the first container (older code changes) when the
  first container successfully deploys.
- Only reap containers that are NOT building and have a permamnent
  status of failed, failed publishing, or online, or orphaned

diff --git a/scripts/starphleet-reaper b/scripts/starphleet-reaper
--- a/scripts/starphleet-reaper
+++ b/scripts/starphleet-reaper
@@ -8,8 +8,28 @@
 ENCODED_ORDER=$(urlencode "${order}")
 for name in $(lxc-ls | grep --extended-regexp -e "^${ENCODED_ORDER}-([a-f0-9]){7}-([a-f0-9]){7}" | grep --invert-match "${current_service_name}")
 do
-  info "reaping ${name}"
-  stop starphleet_serve_order name="${name}" || true
-  starphleet-lxc-destroy "${name}"
-  info "reaper has reaped ${name}"
+STATUS_FILE="${CURRENT_ORDERS}/${order}/.starphleetstatus.${name}"
+
+  # If the status file exists get the status
+  [ -f "${CURRENT_ORDERS}/${order}/.starphleetstatus.${name}" ] &&
+    CURRENT_STATUS=$(cat ${CURRENT_ORDERS}/${order}/.starphleetstatus.${name})
+
+  # Only reap non-building containers.  Being explicit about reap conditions
+  # so future statuses don't trigger accidental reapz
+  # We reap if:
+  #   - The status file doesn't exist (orphaned container)
+  #   - The container is online
+  #   - The container is failed
+  #   - The container failed to publish
+  if [ "${CURRENT_STATUS}" == ""] ||
+     [ "${CURRENT_STATUS}" == "online"] ||
+     [ "${CURRENT_STATUS}" == "failed"] ||
+     [ "${CURRENT_STATUS}" == "publish failed"]; then
+
+    info "reaping ${name}"
+    stop starphleet_serve_order name="${name}" || true
+    starphleet-lxc-destroy "${name}"
+    rm ${CURRENT_ORDERS}/${order}/.starphleetstatus.${name}* 2> /dev/null || true
+    info "reaper has reaped ${name}"
+  fi
 done
