actually getting the redirect stuff to work, turned out to be slightly more than the original PR

diff --git a/scripts/starphleet-publish b/scripts/starphleet-publish
--- a/scripts/starphleet-publish
+++ b/scripts/starphleet-publish
@@ -45,16 +45,11 @@ REDIRECT_CONF="${NGINX_CONF}/published/${order}.redirect"
 PROXY_FOR_CONF="${NGINX_CONF}/proxy_for/${order}.conf"
 SERVER_NAMES_CONF="${NGINX_CONF}/named_servers/${order}.conf"
 
-IP_ADDRESS=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.ip")
-PORT=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.port")
-
-info publishing to ${IP_ADDRESS}
-
-# If we can't get an IP, punt.  THis can happen if a person manually deletes things
-# in CURRENT_ORDERS or tries a starphleet-redeploy which indentionally wipes the world
-if [ -z "${IP_ADDRESS}" ]; then
-  error "Could not find ip address for container ${container_name} cannot publish"
-  exit 1
+if [ -r "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.ip" ]; then
+  IP_ADDRESS=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.ip")
+fi
+if [ -r "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.port" ]; then
+  PORT=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.port")
 fi
 
 mkdir -p "${NGINX_CONF}/published"
@@ -71,11 +66,20 @@ if [ -n "${REDIRECT_TO_SERVICE}" ]; then
   # redirect service is exlusive of all other settings
   cat << EOF > "${MOUNT_CONF}"
 location ${public_url}/ {
-  return 301 ${REDIRECT_TO_SERVICE};
+  rewrite ^${public_url}/(.*)$ ${REDIRECT_TO_SERVICE}/\$1 permanent;
 }
 EOF
   # that's all it does
   exit
+fi
+
+info publishing to ${IP_ADDRESS}
+
+# If we can't get an IP, punt.  THis can happen if a person manually deletes things
+# in CURRENT_ORDERS or tries a starphleet-redeploy which indentionally wipes the world
+if [ -z "${IP_ADDRESS}" ]; then
+  error "Could not find ip address for container ${container_name} cannot publish"
+  exit 1
 fi
 
 #basic publication at an url mount point
