merging in the latest changes from master for publish

diff --git a/scripts/starphleet-publish b/scripts/starphleet-publish
--- a/scripts/starphleet-publish
+++ b/scripts/starphleet-publish
@@ -48,16 +48,11 @@ REDIRECT_CONF="${NGINX_CONF}/published/${order}.redirect"
 PROXY_FOR_CONF="${NGINX_CONF}/proxy_for/${order}.conf"
 SERVER_NAMES_CONF="${NGINX_CONF}/named_servers/${order}.conf"
 
-IP_ADDRESS=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.ip")
-PORT=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.port")
-
-info publishing to ${IP_ADDRESS}
-
-# If we can't get an IP, punt.  THis can happen if a person manually deletes things
-# in CURRENT_ORDERS or tries a starphleet-redeploy which indentionally wipes the world
-if [ -z "${IP_ADDRESS}" ]; then
-  error "Could not find ip address for container ${container_name} cannot publish"
-  exit 1
+if [ -r "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.ip" ]; then
+  IP_ADDRESS=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.ip")
+fi
+if [ -r "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.port" ]; then
+  PORT=$(cat "${CURRENT_ORDERS}/${ORIGINAL_ORDER_NAME}/.starphleetstatus.${container_name}.port")
 fi
 
 mkdir -p "${NGINX_CONF}/published"
@@ -69,6 +64,27 @@ mkdir -p "${NGINX_CONF}/published_secure"
 
 [ -f "${NGINX_CONF}/published/crt" ] || cp "${NGINX_CONF}/crt" "${NGINX_CONF}/published/crt"
 [ -f "${NGINX_CONF}/published/key" ] || cp "${NGINX_CONF}/key" "${NGINX_CONF}/published/key"
+
+if [ -n "${REDIRECT_TO_SERVICE}" ]; then
+  trace "setting service redirect for order ${order} to ${REDIRECT_TO_SERVICE}"
+  # redirect service is exlusive of all other settings
+  cat << EOF > "${MOUNT_CONF}"
+location ${public_url}/ {
+  rewrite ^${public_url}/(.*)$ ${REDIRECT_TO_SERVICE}/\$1 permanent;
+}
+EOF
+  # that's all it does
+  exit
+fi
+
+info publishing to ${IP_ADDRESS}
+
+# If we can't get an IP, punt.  THis can happen if a person manually deletes things
+# in CURRENT_ORDERS or tries a starphleet-redeploy which indentionally wipes the world
+if [ -z "${IP_ADDRESS}" ]; then
+  error "Could not find ip address for container ${container_name} cannot publish"
+  exit 1
+fi
 
 #basic publication at an url mount point
 cat << EOF > "${MOUNT_CONF}"
@@ -117,6 +133,7 @@ cat << EOF >> "${MOUNT_CONF}"
   # WebSocket support (nginx 1.4)
   proxy_http_version 1.1;
   proxy_set_header Upgrade \$http_upgrade;
+  proxy_set_header X-Http \$https;
   proxy_set_header Connection "upgrade";
   more_set_headers 'X-Starphleet-Service: ${public_url}';
   more_set_headers 'X-Starphleet-Container: ${container_name}';
@@ -149,14 +166,16 @@ if [ "${SECURITY_MODE}" = 'ldap' ]; then
   echo "  proxy_set_header ${USER_IDENTITY_HEADER} \$remote_user;" >> "${MOUNT_CONF}"
   echo "  add_header Set-Cookie ${USER_IDENTITY_COOKIE}=\$remote_user;" >> "${MOUNT_CONF}"
 fi
-if [ "${SECURITY_MODE}" != 'public' ] && ! dev_mode ; then
-  # don't want to ldap authenticate from other containers on the ship
-  # see http://forum.nginx.org/read.php?2,242713,242742#msg-242742
-  # note: this needs an auth_basic that alway fails and has the same name as auth_ldap
-  echo "  satisfy any;" >> "${MOUNT_CONF}"
-  echo "  allow 192.168.0.0/16;" >> "${MOUNT_CONF}"
-  echo "  allow 10.0.0.0/8;" >> "${MOUNT_CONF}"
-  echo "  allow 172.16.0.0/12;" >> "${MOUNT_CONF}"
+if [ -z "${DISABLE_AUTO_AUTH}" ]; then
+  if [ "${SECURITY_MODE}" != 'public' ] && ! dev_mode ; then
+    # don't want to ldap authenticate from other containers on the ship
+    # see http://forum.nginx.org/read.php?2,242713,242742#msg-242742
+    # note: this needs an auth_basic that alway fails and has the same name as auth_ldap
+    echo "  satisfy any;" >> "${MOUNT_CONF}"
+    echo "  allow 192.168.0.0/16;" >> "${MOUNT_CONF}"
+    echo "  allow 172.16.0.0/12;" >> "${MOUNT_CONF}"
+    echo "  allow 10.0.0.0/8;" >> "${MOUNT_CONF}"
+  fi
 fi
 
 #closing off the location
