Uniq the acl files

diff --git a/scripts/starphleet-nginx-acl-rules b/scripts/starphleet-nginx-acl-rules
--- a/scripts/starphleet-nginx-acl-rules
+++ b/scripts/starphleet-nginx-acl-rules
@@ -46,10 +46,17 @@ for FILE_ORDERS in $(find ${HEADQUARTERS_LOCAL} -type f -name "orders"); do
   # Go through every ACL file and append the users to a map
   for FILE_ACL_LIST in $(find ${SERVICE_DIR} -type f -name "*.acl"); do
     info loading ACL for service ${SERVICE_NAME} from ${FILE_ACL_LIST}
+    # Map files must have 'uniq' entries so.. lets uniq'ify it
+    FILE_UNIQ_ACL_LIST="/tmp/${SERVICE_NAME}_acl_list.tmp"
+    # In case of errors lets cleanup
+    trap "test -f ${FILE_UNIQ_ACL_LIST} && rm ${FILE_UNIQ_ACL_LIST} 2> /dev/null" SIGTERM EXIT
+    # Uniqify
+    cat "${FILE_ACL_LIST}" | sort | uniq > "${FILE_UNIQ_ACL_LIST}"
     # Add all the users from this file to the map
-    for ACL_USERNAME in $(cat "${FILE_ACL_LIST}"); do
+    for ACL_USERNAME in $(cat "${FILE_UNIQ_ACL_LIST}"); do
       echo "   ${ACL_USERNAME} 1;" >> "${FILE_ACL_RULES_MAP}"
     done
+    [ -f "${FILE_UNIQ_ACL_LIST}" ] && rm "${FILE_UNIQ_ACL_LIST}"
   done
   # If there were ACL files we need to close up the map file
   if [ -n "${HAS_ACL}" ]; then
