checking for presence of IP address during publish, as it's necessary and a blank IP address leads to corrupt nginx configs that affect all services

diff --git a/scripts/starphleet-publish b/scripts/starphleet-publish
--- a/scripts/starphleet-publish
+++ b/scripts/starphleet-publish
@@ -27,6 +27,11 @@ IP_ADDRESS=$(lxc-ls --fancy | grep "^${container_name}" | awk '{ print $3; }')
 
 info publishing to ${IP_ADDRESS}
 
+if [ -z "${IP_ADDRESS}" ]; then
+  error "could not find ip address for container ${container_name} cannot publish"
+  exit 1
+fi
+
 test ! -d "${NGINX_CONF}/published" && mkdir -p "${NGINX_CONF}/published"
 test ! -d "${NGINX_CONF}/published_bare" && mkdir -p "${NGINX_CONF}/published_bare"
 
