Adjust ASG Install Script
- The ASG Install script presumes a pre-existing Starphleet
  skeleton already exists on the AMI.  Make this script a
  bit more resilient to a fresh linux install

diff --git a/scripts/update-starphleet-code-from-userdata b/scripts/update-starphleet-code-from-userdata
--- a/scripts/update-starphleet-code-from-userdata
+++ b/scripts/update-starphleet-code-from-userdata
@@ -17,7 +17,10 @@ if [ -z "${REPO_URL}" -o -z "${REPO_BRANCH}" ]; then
   exit 1
 fi
 echo "upadting starphleet codebase using repo url: ${REPO_URL} and branch ${REPO_BRANCH}"
-rm -rf /starphleet
-git clone ${REPO_URL} /starphleet
-cd /starphleet && git checkout ${REPO_BRANCH}
-./scripts/perform-overlay
+# Set -e above so this might fail sometimes on a new machine, thus || true
+rm -rf /starphleet || true
+# Adjusting slightly to prep a machine that doesn't already have
+# the skelleton of Starphleet
+git clone -b "${REPO_BRANCH}" "${REPO_URL}" /starphleet
+cp /starphleet/scripts/starphleet-launcher /usr/bin
+/starphleet/scripts/perform-overlay
